[[redirects]]
  from = "/"
  to = "https://google.com"
  status = 301
  force = true

[[redirects]]
  from = "/kktgst4pm"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/n4vk1wub0"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/users"
  to = "/index.html"
  status = 200
