[[redirects]]
  from = "/"
  to = "https://google.com"
  status = 301
  force = true

[[redirects]]
  from = "/kktgst4pm"
  to = "first.html"
  status = 302

/kktgst4pm    /index.html    200
/n4vk1wub0    /index.html    200
/api/users    /index.html    200
